#!/bin/bash
echo 'PaaS Service is starting'

./auto-configure

/etc/init.d/haproxy start
/etc/init.d/ssh start
/etc/init.d/cron start
./webssh/webssh > /dev/null &
sleep 8

if [ -f LINKID ]
then
     echo "Find LINKID"
     dropbear config add-authtoken `cat LINKID` > /dev/null
     dropbear http 80  > /dev/null
else
     echo "Can't find LINKID"
     dropbear config add-authtoken "$LINKID" > /dev/null
     dropbear http 80 > /dev/null
fi
